# Generated by Django 4.2.16 on 2024-11-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_profile_bio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer", old_name="user", new_name="author",
        ),
        migrations.RenameField(
            model_name="question", old_name="user", new_name="author",
        ),
        migrations.RenameField(model_name="tag", old_name="tag", new_name="name",),
    ]
