# Generated by Django 4.2.16 on 2024-12-17 15:39

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_answer_is_correct_answerlike_type_questionlike_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerlike",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answerlike",
                to="app.answer",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=pathlib.PurePosixPath(
                    "/Users/ekaterinafedina/ASKME_FEDIN_ANDREY/askme_fedin/media"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="questionlike",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questionlike",
                to="app.question",
            ),
        ),
    ]
